[auth]
redirect_uri="http://localhost:8501/oauth2callback"
cookie_secret="yDZs3424qxcHpaqm8XtDrMJjUqSY/i/FxwM0BANIZPA="
client_id="150888076756-2bmdtgo7s7v00elaqnpg0mcgf16d88nr.apps.googleusercontent.com"
client_secret="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"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"  # fmt: skip